// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAgendamento.Repository.Data;

namespace SistemaAgendamento.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230913233337_MigracaoInicial")]
    partial class MigracaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("SistemaAgendamento.Domain.Models.Agendamento", b =>
                {
                    b.Property<byte[]>("IdAgendamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime>("DiaHoraAgendamento")
                        .HasColumnType("DateTime");

                    b.Property<int?>("EstabelecimentoIDEstabelecimentoIdEstabelecimento")
                        .HasColumnType("int");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeProcedimento")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StatusAgendamento")
                        .HasColumnType("int");

                    b.HasKey("IdAgendamento");

                    b.HasIndex("EstabelecimentoIDEstabelecimentoIdEstabelecimento");

                    b.ToTable("Agendamento");
                });

            modelBuilder.Entity("SistemaAgendamento.Domain.Models.Estabelecimento", b =>
                {
                    b.Property<int>("IdEstabelecimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("NomeEstabelecimento")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeProfissional")
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdEstabelecimento");

                    b.ToTable("Estabelecimento");
                });

            modelBuilder.Entity("SistemaAgendamento.Domain.Models.Agendamento", b =>
                {
                    b.HasOne("SistemaAgendamento.Domain.Models.Estabelecimento", "EstabelecimentoIDEstabelecimento")
                        .WithMany()
                        .HasForeignKey("EstabelecimentoIDEstabelecimentoIdEstabelecimento");

                    b.Navigation("EstabelecimentoIDEstabelecimento");
                });
#pragma warning restore 612, 618
        }
    }
}
